name: "Release"

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - name: Enable Macos
        run: flutter config --enable-macos-desktop
      - name: Build macOS app
        run: flutter build macos --release
      - name: Create a dmg
        run: |
          echo "Install create-dmg"
          brew install create-dmg

          cd build/macos/Build/Products/Release &&
          create-dmg --volname notepad_sqflite \
            --window-pos 200 120 \
            --window-size 800 529 \
            --icon-size 130 \
            --text-size 14 \
            --icon "notepad_sqflite.app" 260 250 \
            --hide-extension "notepad_sqflite.app" \
            --app-drop-link 540 250 \
            --hdiutil-quiet \
            "notepad_sqflite.dmg" \
            "notepad_sqflite.app"

      - name: Publish archives and packages
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/macos/Build/Products/Release/notepad_sqflite.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
