name: "Release"

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: macos-latest
    env:
      MACOS_APP_RELEASE_PATH: build/macos/Build/Products/Release
      APP_NAME: notepad_sqflite
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - name: Enable Macos
        run: flutter config --enable-macos-desktop
      - name: Build macOS app
        run: flutter build macos --release
      - name: Create a dmg
        run: |
          echo "Install create-dmg"
          brew install create-dmg

          cd $MACOS_APP_RELEASE_PATH

          create-dmg \
            --volname "$APP_NAME" \
            --window-pos 200 120 \
            --window-size 800 529 \
            --icon-size 130 \
            --text-size 14 \
            --icon "$APP_NAME.app" 260 250 \
            --hide-extension "$APP_NAME.app" \
            --app-drop-link 540 250 \
            --hdiutil-quiet \
            "$APP_NAME.dmg" \
            "$APP_NAME.app"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.versions.outputs.version }}
          release_name: Release ${{ steps.versions.outputs.version }}
      - name: Publish archives and packages
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: $MACOS_APP_RELEASE_PATH/$APP_NAME.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
